version: '3'
services:
  my-node-app:
    # building Dockerfile, specify the path
    build: .
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo-DB

  mongo-DB:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=moris
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

  # redis:
  #   image: redis
    

volumes:
  mongo-db: